** Project: "Global Earthquake Activity Tracker"
This introduces students to real-world tabular data using Pandas, focusing on reading, exploring, and basic filtering.
The Scenario: You act as junior seismologists analyzing recent global earthquake data.
* Data Structures: You separate out specific columns, like the magnitude, to see how it behaves as an isolated 1D Series compared to the 2D DataFrame context.
* Data I/O: You start by loading the data using pd.read_csv(). Later, you will export their filtered findings using .to_excel() or .to_json() for a web team to use.
* Initial Data Inspection: Before doing anything, you must run .info() and .describe() to understand the sheer volume of data, use .head() to see the layout, and use .value_counts() to see which regions have the most frequent seismic activity.
* Indexing and Selection: * Column/Label/Integer: Use dictionary-style selection to grab the 'Location' column. Use .iloc[] to extract the top 5 largest earthquakes based on row position.
* Filtering: Apply multiple boolean conditions using & and | to find earthquakes that are both greater than magnitude 6.0 and occurred in a specific region (e.g., "Japan" or “Texas”).

In [260]:
# import pandas as pd 

# df = pd.read_csv('earthquake.csv')

# df.to_excel('Tracker.xlsx', index=False)     { this two of this use input/output }
# print(df.columns)

# print(Magnitude.mean()) # average
# print(Magnitude.max())
# print(Magnitude.min())

# Magnitude = df['mag']
# mag_series = pd.Series(data=Magnitude)
# print(mag_series)       # this is 1D

# data = {
#     'place': df['place'],
#     'status': df['status'],
#     'type': df['type']
# }
# df = pd.DataFrame(data)  
# print(df)               # 2D Tabular Data       

# df.head()
# df.describe()
# df.sample(5)
# df.tail()

# # we can use this to see the columns by using .head()
# location_column = df[['mag', 'nst', 'place']]
# print(location_column.head(3))       # Now print the first 3 rows 

# df['mag'].value_counts()  # this is use to show and count how much of that item 
# # -> after using .value_counts() we see that the mag uper than 6 have only one

# print(df.info())
# print(df.index)
# print(df.shape)

# #       { -->>>    putting row for the item in the list and can slicing form it }
# data_selection = {
#     'Name': df['place'],
#     'Status': df['status'],
#     'Type': df['type'],
#     'Mag': df['mag']
# }
# selection = pd.DataFrame(data_selection)
# selection.index = [f'row{i+1}' for i in range(len(selection))]
# # print(selection)

# selection.head()
# selection.tail()
# selection.sample(5)

# #        { -->>> uisng .loc[] && .iloc[] }
# print(selection.loc[['row1','row2','row3','row4'], ['Name', 'Mag']])

# # we using .iloc() using to selction or slicing the item
# print(selection.iloc[0:10, 3:4])

# #      {  FINDING THE TOP 5 OF EARTHQUAKES }

# selection = df.sort_values(by='mag', ascending=False)
# top_5_earthquakes = selection.head(5)
# top_5_earthquakes = selection.tail(10)

# top_5_columns = top_5_earthquakes[['time', 'latitude', 'longitude', 'depth', 'mag', 'magType', 'nst',
#        'gap', 'dmin', 'rms', 'net', 'id', 'updated', 'place', 'type',
#        'horizontalError', 'depthError', 'magError', 'magNst', 'status',
#        'locationSource', 'magSource']]
# # print(top_5_columns)

# # using this to covert what we have find the top5 of earthquake to excel
# top_5_earthquakes.to_excel('top_5_earthquakes.xlsx', index=False)


# # Boolean conditoion
# largest_than_6 = df['mag'] > 6   # condition is largest than 6
# df[largest_than_6]               # using to print it out so see a data

# # Use 'selection' because that is where you defined 'Mag' and 'Name'
# # Use -1 to grab the last item after the comma
# selection['Country/State'] = selection['Name'].str.split(',').str[-1].str.strip()

# #            ->>> Print to check the result
# print(selection[['Country/State', 'Name']].head())

# largest_than_6_and_Japan = (selection['Mag'] > 6) & (selection['Country/State'] == 'Japan')
# print(selection[largest_than_6_and_Japan])             # "The earthquake in Japan was only a 5.9, not a 6.0."


# largest_than_6_and_Japan = (selection['Mag'] > 6) | (selection['Country/State'] == 'Japan')
# selection[largest_than_6_and_Japan]

Index(['time', 'latitude', 'longitude', 'depth', 'mag', 'magType', 'nst',
       'gap', 'dmin', 'rms', 'net', 'id', 'updated', 'place', 'type',
       'horizontalError', 'depthError', 'magError', 'magNst', 'status',
       'locationSource', 'magSource'],
      dtype='object')

,time,latitude,longitude,depth,mag,magType,nst,gap,dmin,rms,...,updated,place,type,horizontalError,depthError,magError,magNst,status,locationSource,magSource
228,2026-03-06T14:27:47.626Z,-11.5475,163.1628,8.682,6.3,mww,51,45,3.793,0.93,...,2026-03-07T14:55:34.181Z,"181 km SE of Kirakira, Solomon Islands",earthquake,3.71,5.154,0.047,44.0,reviewed,us,us
341,2026-03-04T17:54:36.733Z,52.2664,176.3634,10.000,6.4,mww,115,50,1.359,0.88,...,2026-03-09T18:04:41.347Z,"224 km ESE of Attu Station, Alaska",earthquake,5.15,1.820,0.030,104.0,reviewed,us,us
428,2026-03-03T04:56:46.093Z,2.0420,96.7387,18.000,6.2,mww,236,32,1.112,0.79,...,2026-03-05T02:02:47.917Z,"62 km SE of Sinabang, Indonesia",earthquake,7.93,1.686,0.062,25.0,reviewed,us,us

# This code is more clean than the first one

In [1]:
import pandas as pd

df = pd.read_csv('earthquake.csv')

print(df.columns)

# print(df.size)
# df.head()
# print(df.info())
# print(df.shape)
# print(df.index)

# this is 1D that focus on the item specific one using 'Series'
# Magnitude = df['mag']
# mag_series = pd.Series(data=Magnitude)
# print(mag_series)
# print(mag_series.head())

# 2D using DataFrame
# data = {
    # 'Place': df['place'], 
#     'Mag': df['mag'],
#     'Type': df['type']
# }
# df = pd.DataFrame(data)
# df['Mag'].value_counts()       # this is 2D 

# print(df.head())
# print(df.tail())
# print(df.sample(10))
# df.describe()

# using this to add rows for each item 
# data_selection = {
#     'Place': df['place'],
#     'Status': df['status'],
#     'Type': df['type'],
#     'Mag': df['mag']
# }
# selection = pd.DataFrame(data_selection)

# {    the thing in this colomns using to see the short word of the country
# selection['Country/Status'] = selection['Place'].str.split(',').str[-1].str.strip()
# selection        # using to see all of the data 
# selction.head()  # using to see only head
# }

# selection.index = [f"row{i+1}" for i in range(len(selection))]
# print(selection)
# selection.head()
# selection.describe()
# selection.value_counts()

           # --->>>>>> using this to print a top 5 of 'Mag'

# selection = df.sort_values(by='mag', ascending=False)
# top_5_earthquake = selection.head(10)
# top_5_earthquake

# we using this to conver the list in this code to an excel by using .xlsx
# top_5_earthquake.to_excel('top_5_earthquake.xlsx', index=False)
# selection.sample(5)
# selection.tail(10)


# largest_than_6 = df['mag'] >= 6
# print(largest_than_6)
# df[largest_than_6]


# This { is talking about comparison part }

# if u want to print this u need to checking an data first

df['Country/Status'] = df['place'].str.split(',').str[-1].str.strip()
df.index = [f"row{i+1}" for i in range(len(df))]
selection = df.sort_values(by='mag', ascending=False)
# selection.head()  # using to see the header data

# largest_than_5_and_Japan = (selection['mag'] > 5) & (selection['place'] == 'Japan')
# largest_than_5_and_Japan = selection['Country/Status'] == 'Japan'
# selection[largest_than_5_and_Japan].head()

# this condition is mean that the columns that 'Mag' largest than 5 and plac
largest_than_5_and_Japan = (selection['mag'] > 5) | (selection['place'] == 'Japan')
selection[largest_than_5_and_Japan].head()

Index(['time', 'latitude', 'longitude', 'depth', 'mag', 'magType', 'nst',
       'gap', 'dmin', 'rms', 'net', 'id', 'updated', 'place', 'type',
       'horizontalError', 'depthError', 'magError', 'magNst', 'status',
       'locationSource', 'magSource'],
      dtype='object')

,time,latitude,longitude,depth,mag,magType,nst,gap,dmin,rms,...,place,type,horizontalError,depthError,magError,magNst,status,locationSource,magSource,Country/Status
row342,2026-03-04T17:54:36.733Z,52.2664,176.3634,10.000,6.4,mww,115,50,1.359,0.88,...,"224 km ESE of Attu Station, Alaska",earthquake,5.15,1.820,0.030,104.0,reviewed,us,us,Alaska
row229,2026-03-06T14:27:47.626Z,-11.5475,163.1628,8.682,6.3,mww,51,45,3.793,0.93,...,"181 km SE of Kirakira, Solomon Islands",earthquake,3.71,5.154,0.047,44.0,reviewed,us,us,Solomon Islands
row429,2026-03-03T04:56:46.093Z,2.0420,96.7387,18.000,6.2,mww,236,32,1.112,0.79,...,"62 km SE of Sinabang, Indonesia",earthquake,7.93,1.686,0.062,25.0,reviewed,us,us,Indonesia
row15,2026-03-09T23:03:54.405Z,40.5650,14.0671,381.687,6.0,mww,151,29,0.601,0.75,...,"12 km W of Anacapri, Italy",earthquake,6.25,4.506,0.045,47.0,reviewed,us,us,Italy
row90,2026-03-08T17:08:42.581Z,51.6210,159.3956,16.000,5.9,mww,102,44,1.477,0.90,...,"160 km SSE of Vilyuchinsk, Russia",earthquake,9.12,1.843,0.048,41.0,reviewed,us,us,Russia